spring.application.name=AssignmentJV6
#spring.application.name=Lab1Java6
server.port=8282


# 1. URL kết nối (Nhớ đổi tên Database cho đúng với tên bạn đã tạo)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=J6Assignment;encrypt=true;trustServerCertificate=true

# 2. Tài khoản SQL Server (Mặc định thường là sa)
spring.datasource.username=sa
spring.datasource.password=Password@123

# 3. Driver (Bắt buộc cho SQL Server)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate Dialect (Chỉ rõ cho Hibernate biết đây là SQL Server)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Log SQL ra console để dễ debug
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

